
import LbryClasses.Authors;
import LbryClasses.Gender;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ammar
 */
public class jfrmAuthors extends javax.swing.JFrame {
    
    DefaultTableModel dtAuthors;
    
    int authorID = 0;
    
    lbrRMI _rmi;
    Registry reg;

    /**
     * Creates new form jfrmAuthors
     */
    public jfrmAuthors() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        dtAuthors= new DefaultTableModel();
        dtAuthors.addColumn("authorID");
        dtAuthors.addColumn("First Name");
        dtAuthors.addColumn("Middel Name");
        dtAuthors.addColumn("Last Name");
        dtAuthors.addColumn("Gender");
        dtAuthors.addColumn("Nationality");
        
        this.jtblAuthors.setModel(dtAuthors);
        jtblAuthors.getColumnModel().getColumn(0).setWidth(0);
        jtblAuthors.getColumnModel().getColumn(0).setMinWidth(0);
        jtblAuthors.getColumnModel().getColumn(0).setMaxWidth(0);
        
        try {
            reg=LocateRegistry.getRegistry("127.0.0.1", 1099);
            _rmi=(lbrRMI) reg.lookup("myBind");
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (NotBoundException ex) {
            Logger.getLogger(jfrmMembers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtFirstName = new javax.swing.JTextField();
        jtxtLastName = new javax.swing.JTextField();
        jtxtMiddelName = new javax.swing.JTextField();
        jcbxGender = new javax.swing.JComboBox<>();
        jbtnSave = new javax.swing.JButton();
        jbtnSearch = new javax.swing.JButton();
        jbtnClearFrame = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jcbxNationality = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAuthors = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Author Registration Form");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("First Name");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Middel Name");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Last Name");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gender");

        jcbxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnSearch.setText("Search");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jbtnClearFrame.setText("Clear Form");
        jbtnClearFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearFrameActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nationality");

        jcbxNationality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Others -", "Afghans", "Albanians", "Algerians", "Americans", "Andorrans", "Angolans", "Argentines", "Armenians", "Aromanians", "Arubans", "Australians", "Austrians", "Azerbaijanis", "Bahamians", "Bahrainis", "Baltic Germans", "Baltic Russians", "Bangladeshis", "Barbadians", "Basotho", "Basques", "Belarusians", "Belgians", "Belizeans", "Bermudians", "Boers", "Bosniaks", "Brazilians", "Bretons", "British", "British Virgin Islanders", "Bruneians", "Bulgarians", "Burkinabès", "Burundians", "Cambodians", "Cameroonians", "Canadians", "Cape Verdeans", "Catalans", "Chadians", "Chileans", "Chinese", "Colombians", "Comorians", "Congolese", "Croatians", "Cubans", "Cypriots", "Czechs", "Danes", "Dominicans (Commonwealth)", "Dominicans (Republic)", "Dutch", "East Timorese", "Ecuadorians", "Egyptians", "Emiratis", "English", "Eritreans", "Estonians", "Ethiopians", "Falkland Islanders", "Faroese", "Fijians", "Filipinos", "Finnish Swedish", "Finns", "French citizens", "Georgians", "Germans", "Ghanaians", "Gibraltar", "Greek Macedonians", "Greeks", "Grenadians", "Guatemalans", "Guianese (French)", "Guinea-Bissau nationals", "Guineans", "Guyanese", "Haitians", "Hondurans", "Hong Kong", "Hungarians", "Icelanders", "I-Kiribati", "Indians", "Indonesians", "Iranians", "Iraqis", "Irish", "Israelis", "Italians", "Ivoirians", "Jamaicans", "Japanese", "Jordanians", "Kazakhs", "Kenyans", "Koreans", "Kosovars", "Kurds", "Kuwaitis", "Kyrgyzs", "Lao", "Latvians", "Lebanese", "Liberians", "Libyans", "Liechtensteiners", "Lithuanians", "Luxembourgers", "Macao", "Macedonian Bulgarians", "Macedonians", "Malagasy", "Malawians", "Malaysians", "Maldivians", "Malians", "Maltese", "Manx", "Mauritians", "Mexicans", "Moldovans", "Mongolians", "Montenegrins", "Moroccans", "Namibians", "Nepalese", "New Zealanders", "Nicaraguans", "Nigerians", "Nigeriens", "Norwegians", "Pakistanis", "Palauans", "Palestinians", "Panamanians", "Papua New Guineans", "Paraguayans", "Peruvians", "Poles", "Portuguese", "Puerto Ricans", "Quebecers", "Réunionnais", "Romanians", "Russians", "Rwandans", "Salvadorans", "São Tomé and Príncipe", "Saudis", "Scots", "Senegalese", "Serbs", "Sierra Leoneans", "Sindhian", "Singaporeans", "Slovaks", "Slovenes", "Somalilanders", "Somalis", "South Africans", "Spaniards", "Sri Lankans", "St Lucians", "Sudanese", "Surinamese", "Swedes", "Swiss", "Syriacs", "Syrians", "Taiwanese", "Tajik", "Tanzanians", "Thais", "Tibetans", "Tobagonians", "Trinidadians", "Tunisians", "Turkish Cypriots", "Turks", "Tuvaluans", "Ugandans", "Ukrainians", "Uruguayans", "Uzbeks", "Vanuatuans", "Venezuelans", "Vietnamese", "Welsh", "Yemenis", "Zambians", "Zimbabweans" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(jcbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jcbxNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jbtnClearFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jtxtMiddelName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtMiddelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnClearFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtblAuthors.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtblAuthors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblAuthors.setRowHeight(20);
        jtblAuthors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblAuthorsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblAuthors);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed

        if("".equals(this.jtxtFirstName.getText()) ||
            ("".equals(this.jtxtMiddelName.getText()) &&
                "".equals(this.jtxtLastName.getText())))
        {
            JOptionPane.showMessageDialog(this, "Please Insert Author's Name before you proceed.");
            return;
        }

        Authors author;
        author = new Authors(this.authorID, this.jtxtFirstName.getText(),
            this.jtxtMiddelName.getText(),this.jtxtLastName.getText(),
            Gender.getValueOf(this.jcbxGender.getSelectedItem().toString()),
            this.jcbxNationality.getSelectedItem().toString());
        
        try {
            boolean recordSaved = _rmi.AddAuthors(author);
            if(recordSaved){
                JOptionPane.showMessageDialog(this, "Record Saved Successfully");
                this.jbtnSearchActionPerformed(evt);
            }
            else{
                JOptionPane.showMessageDialog(this, "Sorry, Unable to save Record");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(jfrmMembers.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.jbtnClearFrameActionPerformed(evt);
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed

        this.dtAuthors.getDataVector().removeAllElements();
        ArrayList<Authors> allAuthors;
        Object[] ob;

        try {
            allAuthors =  _rmi.fetchAllAuthors();
            for (int i = 0; i < allAuthors.size(); i++) {
                Authors autr = allAuthors.get(i);

                ob=new Object[6];
                ob[0] = autr.AuthorID;
                ob[1] = autr.FirstName;
                ob[2] = autr.MiddelName;
                ob[3] = autr.LastName;
                ob[4] = autr.Gender;
                ob[5] = autr.Nationality;
                this.dtAuthors.addRow(ob);
            }

        } catch (RemoteException ex) {
            Logger.getLogger(jfrmMembers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    private void jbtnClearFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearFrameActionPerformed

        this.authorID = 0;
        this.jtxtFirstName.setText("");
        this.jtxtMiddelName.setText("");
        this.jtxtLastName.setText("");
        this.jcbxGender.setSelectedIndex(0);
        this.jcbxNationality.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnClearFrameActionPerformed

    private void jtblAuthorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblAuthorsMouseClicked
        
        int selectedRowIndex = this.jtblAuthors.getSelectedRow();

        if(selectedRowIndex == -1){
            return;
        }

        this.authorID = (int) this.jtblAuthors.getValueAt(selectedRowIndex, 0);
        this.jtxtFirstName.setText(this.jtblAuthors.getValueAt(selectedRowIndex, 1).toString());
        this.jtxtMiddelName.setText(this.jtblAuthors.getValueAt(selectedRowIndex, 2).toString());
        this.jtxtLastName.setText(this.jtblAuthors.getValueAt(selectedRowIndex, 3).toString());
        this.jcbxGender.setSelectedItem(this.jtblAuthors.getValueAt(selectedRowIndex, 4).toString());
        this.jcbxNationality.setSelectedItem(this.jtblAuthors.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_jtblAuthorsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmAuthors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmAuthors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmAuthors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmAuthors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmAuthors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnClearFrame;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JButton jbtnSearch;
    private javax.swing.JComboBox<String> jcbxGender;
    private javax.swing.JComboBox<String> jcbxNationality;
    private javax.swing.JTable jtblAuthors;
    private javax.swing.JTextField jtxtFirstName;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtMiddelName;
    // End of variables declaration//GEN-END:variables
}
