
import LbryClasses.Users;
import javax.swing.JDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class jfrmMainMenu extends javax.swing.JFrame {

    public Users currentUser;
    /**
     * Creates new form jfrmMainMenu
     */
    public jfrmMainMenu() {
        initComponents();
        
        this.setLocationRelativeTo(null);
                
        if(this.currentUser != null){
        this.jLabel1.setText("Welcome " + this.currentUser.UserName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnMAuthors = new javax.swing.JButton();
        jbtnMuser = new javax.swing.JButton();
        jbtnMCounter = new javax.swing.JButton();
        jbtnMBooks = new javax.swing.JButton();
        jbtnMCataloge = new javax.swing.JButton();
        jbtnMMembers = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtnMAuthors.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMAuthors.setText("Manage Authors");
        jbtnMAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMAuthorsActionPerformed(evt);
            }
        });

        jbtnMuser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMuser.setText("Manage Users");
        jbtnMuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMuserActionPerformed(evt);
            }
        });

        jbtnMCounter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMCounter.setText("Manage Library Counter");
        jbtnMCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMCounterActionPerformed(evt);
            }
        });

        jbtnMBooks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMBooks.setText("Manage Books");
        jbtnMBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMBooksActionPerformed(evt);
            }
        });

        jbtnMCataloge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMCataloge.setText("Manage Cataloge");
        jbtnMCataloge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMCatalogeActionPerformed(evt);
            }
        });

        jbtnMMembers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnMMembers.setText("Manage Members");
        jbtnMMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMMembersActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnMuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnMAuthors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtnMMembers)
                                    .addComponent(jbtnMCataloge)))
                            .addComponent(jbtnMBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jbtnMCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnMuser, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnMAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnMMembers, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnMCataloge, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnMBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnMCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMuserActionPerformed
        jfrmUsers frmUsers = new jfrmUsers();        
        frmUsers.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnMuserActionPerformed

    private void jbtnMMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMMembersActionPerformed
        new jfrmMembers().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jbtnMMembersActionPerformed

    private void jbtnMAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMAuthorsActionPerformed
        new jfrmAuthors().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jbtnMAuthorsActionPerformed

    private void jbtnMCatalogeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMCatalogeActionPerformed
        new jfrmSubjects().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jbtnMCatalogeActionPerformed

    private void jbtnMBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMBooksActionPerformed
        new jfrmBooks().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jbtnMBooksActionPerformed

    private void jbtnMCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMCounterActionPerformed
        new jfrmCounter().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jbtnMCounterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnMAuthors;
    private javax.swing.JButton jbtnMBooks;
    private javax.swing.JButton jbtnMCataloge;
    private javax.swing.JButton jbtnMCounter;
    private javax.swing.JButton jbtnMMembers;
    private javax.swing.JButton jbtnMuser;
    // End of variables declaration//GEN-END:variables
}
